fragment AboutParts on About {
  __typename
  created
  current
  title
  profile_info
}

fragment PostsParts on Posts {
  __typename
  created
  current
  tags
  title
  ingress
  main
  star
}

fragment ProfilesParts on Profiles {
  __typename
  created
  current
  title
  profile
}

fragment AchievementsParts on Achievements {
  __typename
  created
  end
  organization
  org_link
  title
  location
  loc_link
  references
  ref_link
  techStack
  body
}

fragment QuotesParts on Quotes {
  __typename
  title
  link
  quote
}
