//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  about: About;
  aboutConnection: AboutConnection;
  posts: Posts;
  postsConnection: PostsConnection;
  profiles: Profiles;
  profilesConnection: ProfilesConnection;
  achievements: Achievements;
  achievementsConnection: AchievementsConnection;
  quotes: Quotes;
  quotesConnection: QuotesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QueryPostsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostsFilter>;
};


export type QueryProfilesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProfilesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProfilesFilter>;
};


export type QueryAchievementsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAchievementsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AchievementsFilter>;
};


export type QueryQuotesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryQuotesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<QuotesFilter>;
};

export type DocumentFilter = {
  about?: InputMaybe<AboutFilter>;
  posts?: InputMaybe<PostsFilter>;
  profiles?: InputMaybe<ProfilesFilter>;
  achievements?: InputMaybe<AchievementsFilter>;
  quotes?: InputMaybe<QuotesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = About | Posts | Profiles | Achievements | Quotes | Folder;

export type About = Node & Document & {
  __typename?: 'About';
  created: Scalars['String']['output'];
  current?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  profile_info: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type AboutFilter = {
  created?: InputMaybe<DatetimeFilter>;
  current?: InputMaybe<DatetimeFilter>;
  title?: InputMaybe<StringFilter>;
  profile_info?: InputMaybe<RichTextFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type Posts = Node & Document & {
  __typename?: 'Posts';
  created: Scalars['String']['output'];
  current?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  title: Scalars['String']['output'];
  ingress: Scalars['JSON']['output'];
  main: Scalars['JSON']['output'];
  star: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PostsFilter = {
  created?: InputMaybe<DatetimeFilter>;
  current?: InputMaybe<DatetimeFilter>;
  tags?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  ingress?: InputMaybe<RichTextFilter>;
  main?: InputMaybe<RichTextFilter>;
  star?: InputMaybe<RichTextFilter>;
};

export type PostsConnectionEdges = {
  __typename?: 'PostsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Posts>;
};

export type PostsConnection = Connection & {
  __typename?: 'PostsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostsConnectionEdges>>>;
};

export type Profiles = Node & Document & {
  __typename?: 'Profiles';
  created: Scalars['String']['output'];
  current?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  profile: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProfilesFilter = {
  created?: InputMaybe<DatetimeFilter>;
  current?: InputMaybe<DatetimeFilter>;
  title?: InputMaybe<StringFilter>;
  profile?: InputMaybe<RichTextFilter>;
};

export type ProfilesConnectionEdges = {
  __typename?: 'ProfilesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Profiles>;
};

export type ProfilesConnection = Connection & {
  __typename?: 'ProfilesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProfilesConnectionEdges>>>;
};

export type Achievements = Node & Document & {
  __typename?: 'Achievements';
  created: Scalars['String']['output'];
  end?: Maybe<Scalars['String']['output']>;
  organization: Scalars['String']['output'];
  org_link?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  location?: Maybe<Scalars['String']['output']>;
  loc_link?: Maybe<Scalars['String']['output']>;
  references?: Maybe<Scalars['String']['output']>;
  ref_link?: Maybe<Scalars['String']['output']>;
  techStack?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AchievementsFilter = {
  created?: InputMaybe<DatetimeFilter>;
  end?: InputMaybe<DatetimeFilter>;
  organization?: InputMaybe<StringFilter>;
  org_link?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  loc_link?: InputMaybe<StringFilter>;
  references?: InputMaybe<StringFilter>;
  ref_link?: InputMaybe<StringFilter>;
  techStack?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type AchievementsConnectionEdges = {
  __typename?: 'AchievementsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Achievements>;
};

export type AchievementsConnection = Connection & {
  __typename?: 'AchievementsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AchievementsConnectionEdges>>>;
};

export type Quotes = Node & Document & {
  __typename?: 'Quotes';
  title: Scalars['String']['output'];
  link: Scalars['String']['output'];
  quote: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type QuotesFilter = {
  title?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
};

export type QuotesConnectionEdges = {
  __typename?: 'QuotesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Quotes>;
};

export type QuotesConnection = Connection & {
  __typename?: 'QuotesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<QuotesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateAbout: About;
  createAbout: About;
  updatePosts: Posts;
  createPosts: Posts;
  updateProfiles: Profiles;
  createProfiles: Profiles;
  updateAchievements: Achievements;
  createAchievements: Achievements;
  updateQuotes: Quotes;
  createQuotes: Quotes;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdatePostsArgs = {
  relativePath: Scalars['String']['input'];
  params: PostsMutation;
};


export type MutationCreatePostsArgs = {
  relativePath: Scalars['String']['input'];
  params: PostsMutation;
};


export type MutationUpdateProfilesArgs = {
  relativePath: Scalars['String']['input'];
  params: ProfilesMutation;
};


export type MutationCreateProfilesArgs = {
  relativePath: Scalars['String']['input'];
  params: ProfilesMutation;
};


export type MutationUpdateAchievementsArgs = {
  relativePath: Scalars['String']['input'];
  params: AchievementsMutation;
};


export type MutationCreateAchievementsArgs = {
  relativePath: Scalars['String']['input'];
  params: AchievementsMutation;
};


export type MutationUpdateQuotesArgs = {
  relativePath: Scalars['String']['input'];
  params: QuotesMutation;
};


export type MutationCreateQuotesArgs = {
  relativePath: Scalars['String']['input'];
  params: QuotesMutation;
};

export type DocumentUpdateMutation = {
  about?: InputMaybe<AboutMutation>;
  posts?: InputMaybe<PostsMutation>;
  profiles?: InputMaybe<ProfilesMutation>;
  achievements?: InputMaybe<AchievementsMutation>;
  quotes?: InputMaybe<QuotesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  about?: InputMaybe<AboutMutation>;
  posts?: InputMaybe<PostsMutation>;
  profiles?: InputMaybe<ProfilesMutation>;
  achievements?: InputMaybe<AchievementsMutation>;
  quotes?: InputMaybe<QuotesMutation>;
};

export type AboutMutation = {
  created?: InputMaybe<Scalars['String']['input']>;
  current?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  profile_info?: InputMaybe<Scalars['JSON']['input']>;
};

export type PostsMutation = {
  created?: InputMaybe<Scalars['String']['input']>;
  current?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  title?: InputMaybe<Scalars['String']['input']>;
  ingress?: InputMaybe<Scalars['JSON']['input']>;
  main?: InputMaybe<Scalars['JSON']['input']>;
  star?: InputMaybe<Scalars['JSON']['input']>;
};

export type ProfilesMutation = {
  created?: InputMaybe<Scalars['String']['input']>;
  current?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  profile?: InputMaybe<Scalars['JSON']['input']>;
};

export type AchievementsMutation = {
  created?: InputMaybe<Scalars['String']['input']>;
  end?: InputMaybe<Scalars['String']['input']>;
  organization?: InputMaybe<Scalars['String']['input']>;
  org_link?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  loc_link?: InputMaybe<Scalars['String']['input']>;
  references?: InputMaybe<Scalars['String']['input']>;
  ref_link?: InputMaybe<Scalars['String']['input']>;
  techStack?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type QuotesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
};

export type AboutPartsFragment = { __typename: 'About', created: string, current?: string | null, title: string, profile_info: any };

export type PostsPartsFragment = { __typename: 'Posts', created: string, current?: string | null, tags?: Array<string | null> | null, title: string, ingress: any, main: any, star: any };

export type ProfilesPartsFragment = { __typename: 'Profiles', created: string, current?: string | null, title: string, profile: any };

export type AchievementsPartsFragment = { __typename: 'Achievements', created: string, end?: string | null, organization: string, org_link?: string | null, title: string, location?: string | null, loc_link?: string | null, references?: string | null, ref_link?: string | null, techStack?: Array<string | null> | null, body: any };

export type QuotesPartsFragment = { __typename: 'Quotes', title: string, link: string, quote: string };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, created: string, current?: string | null, title: string, profile_info: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, created: string, current?: string | null, title: string, profile_info: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PostsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PostsQuery = { __typename?: 'Query', posts: { __typename: 'Posts', id: string, created: string, current?: string | null, tags?: Array<string | null> | null, title: string, ingress: any, main: any, star: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PostsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostsFilter>;
}>;


export type PostsConnectionQuery = { __typename?: 'Query', postsConnection: { __typename?: 'PostsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PostsConnectionEdges', cursor: string, node?: { __typename: 'Posts', id: string, created: string, current?: string | null, tags?: Array<string | null> | null, title: string, ingress: any, main: any, star: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ProfilesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProfilesQuery = { __typename?: 'Query', profiles: { __typename: 'Profiles', id: string, created: string, current?: string | null, title: string, profile: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProfilesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProfilesFilter>;
}>;


export type ProfilesConnectionQuery = { __typename?: 'Query', profilesConnection: { __typename?: 'ProfilesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProfilesConnectionEdges', cursor: string, node?: { __typename: 'Profiles', id: string, created: string, current?: string | null, title: string, profile: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type AchievementsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AchievementsQuery = { __typename?: 'Query', achievements: { __typename: 'Achievements', id: string, created: string, end?: string | null, organization: string, org_link?: string | null, title: string, location?: string | null, loc_link?: string | null, references?: string | null, ref_link?: string | null, techStack?: Array<string | null> | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AchievementsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AchievementsFilter>;
}>;


export type AchievementsConnectionQuery = { __typename?: 'Query', achievementsConnection: { __typename?: 'AchievementsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AchievementsConnectionEdges', cursor: string, node?: { __typename: 'Achievements', id: string, created: string, end?: string | null, organization: string, org_link?: string | null, title: string, location?: string | null, loc_link?: string | null, references?: string | null, ref_link?: string | null, techStack?: Array<string | null> | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type QuotesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type QuotesQuery = { __typename?: 'Query', quotes: { __typename: 'Quotes', id: string, title: string, link: string, quote: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type QuotesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<QuotesFilter>;
}>;


export type QuotesConnectionQuery = { __typename?: 'Query', quotesConnection: { __typename?: 'QuotesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'QuotesConnectionEdges', cursor: string, node?: { __typename: 'Quotes', id: string, title: string, link: string, quote: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  created
  current
  title
  profile_info
}
    `;
export const PostsPartsFragmentDoc = gql`
    fragment PostsParts on Posts {
  __typename
  created
  current
  tags
  title
  ingress
  main
  star
}
    `;
export const ProfilesPartsFragmentDoc = gql`
    fragment ProfilesParts on Profiles {
  __typename
  created
  current
  title
  profile
}
    `;
export const AchievementsPartsFragmentDoc = gql`
    fragment AchievementsParts on Achievements {
  __typename
  created
  end
  organization
  org_link
  title
  location
  loc_link
  references
  ref_link
  techStack
  body
}
    `;
export const QuotesPartsFragmentDoc = gql`
    fragment QuotesParts on Quotes {
  __typename
  title
  link
  quote
}
    `;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const PostsDocument = gql`
    query posts($relativePath: String!) {
  posts(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostsParts
  }
}
    ${PostsPartsFragmentDoc}`;
export const PostsConnectionDocument = gql`
    query postsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostsFilter) {
  postsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostsParts
      }
    }
  }
}
    ${PostsPartsFragmentDoc}`;
export const ProfilesDocument = gql`
    query profiles($relativePath: String!) {
  profiles(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProfilesParts
  }
}
    ${ProfilesPartsFragmentDoc}`;
export const ProfilesConnectionDocument = gql`
    query profilesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProfilesFilter) {
  profilesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProfilesParts
      }
    }
  }
}
    ${ProfilesPartsFragmentDoc}`;
export const AchievementsDocument = gql`
    query achievements($relativePath: String!) {
  achievements(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AchievementsParts
  }
}
    ${AchievementsPartsFragmentDoc}`;
export const AchievementsConnectionDocument = gql`
    query achievementsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AchievementsFilter) {
  achievementsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AchievementsParts
      }
    }
  }
}
    ${AchievementsPartsFragmentDoc}`;
export const QuotesDocument = gql`
    query quotes($relativePath: String!) {
  quotes(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...QuotesParts
  }
}
    ${QuotesPartsFragmentDoc}`;
export const QuotesConnectionDocument = gql`
    query quotesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: QuotesFilter) {
  quotesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...QuotesParts
      }
    }
  }
}
    ${QuotesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    posts(variables: PostsQueryVariables, options?: C): Promise<{data: PostsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsQueryVariables, query: string}> {
        return requester<{data: PostsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsQueryVariables, query: string}, PostsQueryVariables>(PostsDocument, variables, options);
      },
    postsConnection(variables?: PostsConnectionQueryVariables, options?: C): Promise<{data: PostsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsConnectionQueryVariables, query: string}> {
        return requester<{data: PostsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsConnectionQueryVariables, query: string}, PostsConnectionQueryVariables>(PostsConnectionDocument, variables, options);
      },
    profiles(variables: ProfilesQueryVariables, options?: C): Promise<{data: ProfilesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProfilesQueryVariables, query: string}> {
        return requester<{data: ProfilesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProfilesQueryVariables, query: string}, ProfilesQueryVariables>(ProfilesDocument, variables, options);
      },
    profilesConnection(variables?: ProfilesConnectionQueryVariables, options?: C): Promise<{data: ProfilesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProfilesConnectionQueryVariables, query: string}> {
        return requester<{data: ProfilesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProfilesConnectionQueryVariables, query: string}, ProfilesConnectionQueryVariables>(ProfilesConnectionDocument, variables, options);
      },
    achievements(variables: AchievementsQueryVariables, options?: C): Promise<{data: AchievementsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AchievementsQueryVariables, query: string}> {
        return requester<{data: AchievementsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AchievementsQueryVariables, query: string}, AchievementsQueryVariables>(AchievementsDocument, variables, options);
      },
    achievementsConnection(variables?: AchievementsConnectionQueryVariables, options?: C): Promise<{data: AchievementsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AchievementsConnectionQueryVariables, query: string}> {
        return requester<{data: AchievementsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AchievementsConnectionQueryVariables, query: string}, AchievementsConnectionQueryVariables>(AchievementsConnectionDocument, variables, options);
      },
    quotes(variables: QuotesQueryVariables, options?: C): Promise<{data: QuotesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuotesQueryVariables, query: string}> {
        return requester<{data: QuotesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuotesQueryVariables, query: string}, QuotesQueryVariables>(QuotesDocument, variables, options);
      },
    quotesConnection(variables?: QuotesConnectionQueryVariables, options?: C): Promise<{data: QuotesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuotesConnectionQueryVariables, query: string}> {
        return requester<{data: QuotesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuotesConnectionQueryVariables, query: string}, QuotesConnectionQueryVariables>(QuotesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  